Add support for transform plugins on tunnels.
apache/trafficserver pull request #10314
Opened 2023-08-30 15:32 UTC by shinrich

This requires the tunnel start hook from PR #10308, so this PR is building on that branch. So far only the last commit is unique to this PR.

This closes #10313

2023-09-25 21:54 UTC, moonchen commented
Waiting for conflict resolution.

2023-09-26 20:19 UTC, shinrich commented
Rebased.  Looks like I made a test plugin but didn't actually make an autest to use it.  Will get that added tomorrow.

2023-09-27 17:00 UTC, moonchen requested changes

2023-09-27 17:01 UTC, moonchen commented
Looks good!  Just one small nitpick.

2023-09-27 18:42 UTC, moonchen submitted a review, later dismissed

2023-09-27 22:23 UTC, shinrich commented
[approve ci autest]

2023-09-29 14:11 UTC, shinrich commented on tests/gold_tests/tunnel/tunnel_transform.test.py
> +tr2.Processes.Default.Streams.stdout = Testers.Lambda(lambda info, tester: check_range(path1, 700, 800))
I couldn't figure out how to get the current streams stdout fed into the check_range function.  I assume it is available via the info argument, but that appears to be a structure and I couldn't find the methods to get the data stream.  So I'm testing the output by reading the standard output file from the previous test case (a pattern I had used in some tls tests).  @dragon512 or @bneradt I'd appreciate pointers to clean this up.  Would be happy to do that in a later PR.  This logic is functional and verifies that the metric falls within a range.

2023-10-02 18:26 UTC, moonchen approved these changes

2023-10-02 21:44 UTC, merged