cmake: fix support for je/mi malloc and the mallocallocator
apache/trafficserver pull request #10407
Opened 2023-09-13 05:29 UTC by cmcfarlen

fixes [#10377](https://github.com/apache/trafficserver/issues/10377)

2023-09-17 13:03 UTC, JosiahWI approved these changes
Looks good!

2023-09-18 16:49 UTC, JosiahWI approved these changes

2023-09-21 14:56 UTC, JosiahWI requested changes

2023-09-21 14:56 UTC, JosiahWI commented on CMakeLists.txt
>      link_libraries(mimalloc)
```suggestion
    link_libraries(mimalloc::mimalloc)
```
here too

2023-09-21 22:24 UTC, cmcfarlen commented on CMakeLists.txt
>      link_libraries(mimalloc)
There isn't currently a `mimalloc::mimalloc` target

2023-09-22 18:36 UTC, bryancall commented
Testing malloc:
```
$ cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=/opt/ats -DCMAKE_BUILD_TYPE=Debug -DENABLE_AUTEST=ON -DBUILD_EXPERIMENTAL_PLUGINS=ON -DENABLE_MALLOC_ALLOCATOR=ON
$ cd build; ninja
$ grep -ir TS_USE_MALLOC_ALLOCATOR
include/tscore/ink_config.h:#define TS_USE_MALLOC_ALLOCATOR 1
```

2023-09-22 18:48 UTC, bryancall commented
By default it looks like we enable jemalloc.  I don't believe this is what we do for autotools:
```
CMakeCache.txt:ENABLE_JEMALLOC:STRING=AUTO
CMakeCache.txt:jemalloc_INCLUDE_DIR:PATH=/usr/include/jemalloc
CMakeCache.txt:jemalloc_LIBRARY:FILEPATH=/usr/lib64/libjemalloc.so
```

2023-09-25 21:33 UTC, bryancall commented on include/tscore/ink_memory.h
> +#include <jemalloc.h>
Ee only need to have `#include <jemalloc.h>` in the code for compiling with `cmake`.    The include directory detection add in the subdir `jemalloc`.

However, with autotools we need to have the `#include <jemalloc/jemalloc.h>`

2023-09-25 21:34 UTC, bryancall approved these changes

2023-09-25 21:59 UTC, merged