Improve the TSMgmtUpdateRegister with an optional file name
apache/trafficserver pull request #10642
Opened 2023-10-18 21:28 UTC by zwoop

Providing this filename makes the update registry keep track of file changes automatically. When used, the continuation provided will only be called if changes to the configuration file is detected.

Also, this eliminates the superflous code for calling a named plugin reload. That code is never used, and I don't like having code there "just because", when nothing uses it.

2023-10-19 02:30 UTC, zwoop commented
[approve ci].

2023-10-19 07:37 UTC, shukitchan requested changes
Let's update documentation as well - https://docs.trafficserver.apache.org/en/latest/developer-guide/api/functions/TSMgmtUpdateRegister.en.html

2023-10-21 21:36 UTC, zwoop commented
[approve ci]

2023-10-22 14:56 UTC, zwoop commented
[approve ci autest]

2023-10-22 23:05 UTC, shukitchan commented
[approve ci autest]

2023-10-22 23:15 UTC, shukitchan commented
1) Since it is an API change, should we send an email to the mailing list of the change?

2) The "name" is really useless. So it does not have to be a map. A list will do. Right?. I am ok with the current change unless you want to improve it further.

2023-10-23 00:01 UTC, zwoop commented
> 1. Since it is an API change, should we send an email to the mailing list of the change?

Yeh, I can email, but it doesn't break or modify any existing plugins (because we can now provide defaults in API changes).

> 2. The "name" is really useless. So it does not have to be a map. A list will do. Right?. I am ok with the current change unless you want to improve it further.

With # 2, yes, it's useless, but removing it would break compatibility unnecessarily. I'd rather keep it, if not only because it could at least allow for easier debugging later.

2023-10-23 00:03 UTC, shukitchan approved these changes

2023-10-23 10:22 UTC, brbzull0 approved these changes
looks good!
Thanks.

2023-10-23 19:54 UTC, merged