cmake: add ENABLE_FIPS option
apache/trafficserver pull request #10679
Opened 2023-10-26 15:58 UTC by cmcfarlen

fixes #10678

2023-10-26 16:39 UTC, cmcfarlen commented
[approve ci autest]

2023-10-26 17:34 UTC, JosiahWI requested changes
Looks good. I have just one small nitpick.

2023-10-26 17:34 UTC, JosiahWI commented on include/tscore/ink_config.h.cmake.in
> +#cmakedefine01 TS_ENABLE_FIPS
Shouldn't this go with the other `TS_ENABLE` vars?

2023-10-30 22:25 UTC, bryancall approved these changes

2023-10-31 00:50 UTC, merged