TSFile - remove from background_fetch plugin.
apache/trafficserver pull request #10909
Opened 2023-12-08 16:08 UTC by SolidWallOfCode

`TSFile` and related plugin API are being deprecated. This removes those from the `background_fetch` plugin, along with some other clean up.

2023-12-08 16:35 UTC, SolidWallOfCode commented
https://github.com/apache/trafficserver/blob/master/tests/gold_tests/cache/background_fill.test.py

2023-12-08 16:43 UTC, SolidWallOfCode commented
Hmmm, I'll have to double check.

2023-12-19 19:11 UTC, ezelkow1 requested changes

2023-12-19 19:11 UTC, ezelkow1 commented on plugins/background_fetch/configs.h
that extern DbgCtl Bg_dbg_ctl should probably be

DbgCtl Bg_dbg_ctl{PLUGIN_NAME};

Plugin will build as-is but not run like that due to the externed dbg

2023-12-19 21:21 UTC, ywkaras commented on plugins/background_fetch/configs.h
Could just add:

DbgCtl Bg_dbg_ctl{PLUGIN_NAME};

to config.cc .

2024-01-09 00:00 UTC, bryancall commented
@ezelkow1 is going to take over this PR

2024-03-11 21:35 UTC, bryancall commented
This was fixed with #10980

2024-03-11 21:35 UTC, closed without merging