Segmentation crash caused by setting unavailable_server_retry_responses in parent.config
apache/trafficserver pull request #11009
Opened 2024-01-25 02:52 UTC by jasmine-nahrain

At the moment,  `unavailable_server_retry_responses` and `simple_server_retry_responses` will be nullptr's when parent_retry is enabled and the retry type does not match their type. e.g. parent_retry=SIMPLE_RETRY, `unavailable_server_retry_responses` will be null. But these values are both used in the code no matter what the type is. This has been causing a segmentation fault as the code is trying to use the .contain() method on what is currently a nullptr. This change ensures that they are always initialised with their default values when parent_retry is enabled, irrespective of the retry type.

Should close #11005

2024-01-25 04:18 UTC, jasmine-nahrain commented
[approve ci fedora]

2024-01-28 22:40 UTC, jasmine-nahrain commented
> Shouldn't we add nullptr checks instead because they still can be nullptr if we hit line 783 or 795?
By initialising both fields with their default values, it should not ever be a nullptr. I did it this way in case the values are called in other parts of the code. It means the initial value is never a nullptr.

2024-01-29 18:45 UTC, maskit commented
I may be wrong but this part looks problematic.
https://github.com/apache/trafficserver/blob/f84038734069a2a2562329fecabd575cd4f59009/src/proxy/http/HttpTransact.cc#L420-L422
If we hit line 795, which deletes `simple_server_retry_responses`, doesn't it cause a crash if we reach line 422?

Creating an empty object with `new` just to avoid nullptr dereference sounds costly. I assume this particular code doesn't affect performance because it's called in `Init`, which suggests it's only run on startup. But that's still not a good practice, IMO. Deleting an object right after creating it looks silly too. I'd suggest having actual instances of `UnavailableServerResponseCodes` and `SimpleRetryResponseCodes` instead of pointers for them (in other words, `UnavailableServerResponseCodes` and `SimpleRetryResponseCodes` instead of `UnavailableServerResponseCodes *` and `SimpleRetryResponseCodes *`). This prevents nullptr dereferences and also memory leak.

2024-02-01 23:55 UTC, jasmine-nahrain commented
[approve ci autest]

2024-02-05 23:45 UTC, bneradt requested changes
Thanks for adding an autest.

2024-02-05 23:45 UTC, bneradt commented on tests/gold_tests/parent_proxy/parent-retry.test.py
> +        tr.Processes.Default.Command = 'curl "{}" --verbose'.format(self.ts_child.Variables.port)
We use `f'...'` strings now (like you do above with parent_config) instead of `.format()` for all new tests.

2024-02-07 15:55 UTC, duke8253 approved these changes
Looks good

2024-02-07 16:14 UTC, bneradt approved these changes

2024-02-07 16:23 UTC, merged

2024-02-16 03:00 UTC, zwoop commented
Cherry-picked to v9.2.x