Fix esi-fetcher-plugin libswoc include issue
apache/trafficserver pull request #11011
Opened 2024-01-25 17:54 UTC by phongn

We discovered some linking issues with use of an external libswoc; this fully qualifies inclusion so that internal or external should be usable.

2024-01-26 16:42 UTC, JosiahWI requested changes

2024-01-26 16:42 UTC, JosiahWI commented on plugins/esi/fetcher/CMakeLists.txt
> +target_include_directories(fetcher PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}" "${libswoc_INCLUDE_DIRS}")
We should not be both linking the target and explicitly dumping its `INCLUDE_DIRS` into `target_include_directories`, as linking the target should already do this.

2024-01-29 18:01 UTC, JosiahWI reviewed
Looks good.

2024-01-29 23:35 UTC, cmcfarlen approved these changes

2024-02-02 21:57 UTC, JosiahWI approved these changes

2024-02-02 22:00 UTC, merged