Restore derived metrics using new metrics
apache/trafficserver pull request #11297
Opened 2024-04-26 20:18 UTC by cmcfarlen

2024-04-29 15:22 UTC, bneradt requested changes
Looks good.

2024-04-29 15:22 UTC, bneradt commented on include/tsutil/Metrics.h
> +  {
Let's add doxygen comments explaining the responsibilities and purpose of this class.

2024-04-29 15:22 UTC, bneradt commented on include/tsutil/Metrics.h
> +      std::initializer_list<std::variant<Metrics::AtomicType *, Metrics::IdType, std::string_view>> derived_from;
A using alias for the variant could be helpful here.

2024-04-29 15:22 UTC, bneradt commented on include/tsutil/Metrics.h
> +    static void update_derived();
doxygen

2024-04-29 16:36 UTC, bneradt approved these changes

2024-04-29 22:11 UTC, cmcfarlen commented
https://github.com/apache/trafficserver/blob/9.2.x/mgmt/DerivativeMetrics.cc

2024-04-30 17:57 UTC, merged

2024-05-01 14:52 UTC, cmcfarlen commented
Cherry-picked to v10.0.x