Removed the API TSUrlHttpParamsGet() from the cookie remap plugin
apache/trafficserver pull request #11579
Opened 2024-07-18 20:57 UTC by bryancall

2024-07-18 21:22 UTC, maskit commented
[approve ci]

2024-07-22 22:07 UTC, maskit requested changes
```
$ git grep "matrix param" tests/
tests/gold_tests/pluginTest/cookie_remap/matrixparams.test.py:Test.testName = "cookie_remap: Tests when matrix parameters are present"
tests/gold_tests/pluginTest/cookie_remap/matrixparams.test.py:                      inserting matrix parameters in remap")
tests/gold_tests/pluginTest/cookie_remap/matrixparams.test.py:tr = Test.AddTestRun("inserting matrix params in remap and \
```

2024-07-26 19:54 UTC, maskit approved these changes

2024-07-29 20:28 UTC, merged

2024-07-30 21:18 UTC, cmcfarlen commented
Cherry-picked to v10.0.x