Remove H3 frame sequence number tracking
apache/trafficserver pull request #11632
Opened 2024-07-31 18:50 UTC by maskit

This closes #11622.

The frame sequence was only used for `ProtocolEnforcer` and there is no other use case planned. This PR removes the sequence number tracking, which was reset on every READ_READY, and use a private flag in ProtocolEnforcer to do the same check for SETTINGS frame.

2024-07-31 18:52 UTC, JosiahWI commented on src/proxy/http3/test/test_Http3FrameDispatcher.cc
>    free_MIOBuffer(buf);
Doesn't need to be freed twice.

2024-07-31 18:57 UTC, JosiahWI requested changes
Nice cleanup! Let's not free the buffer in the test twice, though.

2024-07-31 18:59 UTC, JosiahWI commented
The tests for `AggregateWriteBuffer` segfaulted on CentOs. That is unrelated to this change and I will look into it.

2024-07-31 19:50 UTC, maskit commented on src/proxy/http3/test/test_Http3FrameDispatcher.cc
>    free_MIOBuffer(buf);
Good catch.

2024-07-31 19:51 UTC, maskit commented
@JosiahWI Do you want to gather information before I push a new commit and trigger new jenkins jobs?

2024-07-31 19:55 UTC, JosiahWI commented
@maskit I'm not sure I can gather anything useful from the job. I don't know how to get a stack trace. I suspect it's a race condition, but I don't know how it's related to the test or whether it's related at all. The valgrind report on my OpenSUSE container comes up completely clean.

2024-07-31 19:58 UTC, maskit commented
Ok, I'l rerun the job without pushing a new commit to see if it fails again. I'll push a new commit if it doesn't fail.

2024-07-31 19:58 UTC, maskit commented
[approve ci centos]

2024-07-31 20:20 UTC, maskit commented
All tests passed this time.

2024-07-31 20:21 UTC, JosiahWI approved these changes
Thanks for the fix!

2024-07-31 20:57 UTC, maskit commented
```
139/139 Test   #9: test_AIO ...............................***Timeout 1500.06 sec
configuration file: sample.cfg
reading disk_size = 1
reading hotset_size = 1
reading hotset_frequency = 0.5
reading run_time = 30
reading threads_per_disk = 1
reading touch_data = 1
reading seq_read_percent = 0.5
reading seq_write_percent = 0.3
reading rand_read_percent = 0.2
reading seq_read_size = 131072
reading seq_write_size = 4093
reading rand_read_size = 4096
reading write_skip = 5
reading chains = 1
reading delete_disks = 1
reading disk_path = ./aio.tst
reading num_processors = 5
Starting hotset document writing 
Finished hotset documents  [8] offset [  8192] size [131072]
Starting the aio_testing 
=================================================================
==4621==ERROR: AddressSanitizer: heap-use-after-free on address 0x6040000001b8 at pc 0x0000004530d4 bp 0x7f0593db2fa0 sp 0x7f0593db2f90
READ of size 1 at 0x6040000001b8 thread T3 ([ET_NET 2])
```

2024-07-31 20:57 UTC, maskit commented
[approve ci rocky]

2024-07-31 21:07 UTC, merged

2024-08-01 20:33 UTC, cmcfarlen commented
Cherry-picked to v10.0.x