Make error if remap ACL has more than one @action
apache/trafficserver pull request #11911
Opened 2024-12-13 07:45 UTC by masaori335

One remap line or named filter takes only one `@action=`. However, prior to the change, ATS doesn't have check for this on loading remap.config.

2024-12-13 17:16 UTC, bneradt requested changes
Looks good. I just have a suggestion to rephrase.

2024-12-13 17:16 UTC, bneradt commented on src/proxy/http/remap/RemapConfig.cc
> +        std::string_view err = "Only one @action= is available";
`available` -> `allowed per remap ACL`

2024-12-15 23:01 UTC, masaori335 commented on src/proxy/http/remap/RemapConfig.cc
> +        std::string_view err = "Only one @action= is available";
Thank you for suggestion. Updated.

2024-12-16 19:50 UTC, bneradt approved these changes

2024-12-16 23:08 UTC, merged

2024-12-19 01:31 UTC, masaori335 commented
For 9.2.x and 10.0.x, making Warning instead of Error for compatibility. Thus, 10.1.0 and greater will make it Error.

2025-01-06 16:21 UTC, cmcfarlen commented
Cleared milestone for #11925