Unit Test -  Increase openssl's key size. Place test certs into a com…
apache/trafficserver pull request #7451
Opened 2021-01-26 18:20 UTC by brbzull0

Running autest in Fedora 33 with `OpenSSL 1.1.1i` seems to fail. Looking deeper it seems that the key zise policy increased in the newer openssl's.
This Draft contains a few changes:
1 - Regenerate basic certs (server.pem, server.key, signer.pem)
2 - Place the new keys in a common folder(`tests/tools/ssl`) and make relevant unit tests use from this new location.
3 - Update trafficserver.test.ext to export a new functions (`addDefaultSSLFiles` and  `addSSLFileFromDefaultTestFolder`) which can be used to add the files from the new common folder.
4 - Update microserver's certs .

2021-01-26 19:37 UTC, brbzull0 commented
[approve ci autest]

2021-01-26 20:26 UTC, bneradt requested changes
Looks good. One small comment.

Thanks for updating the certs!

2021-01-26 20:26 UTC, bneradt commented on tests/gold_tests/timeout/tls_conn_timeout.test.py
> +tr.Setup.Copy("../../tools/ssl/server.pem")
Instead of ../../tools, I believe we can use the `Test.Variables.AtsTestToolsDir`.

2021-01-28 15:26 UTC, shinrich commented
Good cleanup and update for newer default openssl configs.  Once this lands, I'll do a review of my additional certs in the TLS area.

I think one of the comcast folks (@traeak ?) ran into this issue a few months ago.  A review from him would be good.

2021-01-28 18:18 UTC, randall commented
This is a great PR! Thanks for the work here!

For future us, how does one regenerate the test certs?

2021-01-28 18:55 UTC, brbzull0 commented
> This is a great PR! Thanks for the work here!
> 
> For future us, how does one regenerate the test certs?

Hi @randall 
This [notes](https://github.com/yahoo/proxy-verifier/blob/ac9541ea7dec6a82ee7ea8b0e33249798a91b97e/test/keys/README) were given by @bneradt from Proxy Verifier.

Thanks.

2021-02-04 21:45 UTC, duke8253 commented
Confirmed this is working for Ubuntu as well, started seeing `ssl.SSLError: [SSL: EE_KEY_TOO_SMALL] ee key too small (_ssl.c:4021)` a few days ago.

2021-02-06 00:02 UTC, randall approved these changes

2021-02-06 02:26 UTC, bneradt approved these changes

2021-02-07 19:54 UTC, merged

2021-02-23 17:42 UTC, zwoop commented
Cherry-picked to v9.1.x branch.