Autest - Proxy Verifier Extension, add context template $-base string…
apache/trafficserver pull request #7866
Opened 2021-05-21 10:30 UTC by brbzull0

Add support for `$-base` string   substitution on the passed replay file. 
With this feature we now should be able to have a replay file with `$-base` strings which will be replaced by the PV extension using a context dict-like structure.

A good use case for this would be that a particular PV Server(b) needs to redirect to another PV Server(a) , so the port needs to be part of the host string in the server's(b) replay file:

`my_replaty_file.yaml`
```
....
  server-response:
        status: 302
        reason: Redirect
        headers:
          fields:
          - [ Location, "http://a.test:${a_port}/" ]
```
my unit test
```
... 
Test.MakeVerifierServerProcess("b_server", "my_replaty_file.yaml", 
          context={"a_port": a_server.Variables.http_port})
```

2021-05-21 14:08 UTC, bneradt requested changes
Looks great Damian! Just a few minor suggestions.

2021-05-21 14:08 UTC, bneradt commented on tests/gold_tests/autest-site/verifier_common.py
> +        result = src.substitute(context)
I suggest:
* src -> replay_template
* result -> replay_text

2021-05-21 14:08 UTC, bneradt commented on tests/gold_tests/autest-site/verifier_common.py
> +        replay_path = tf.name
If you move this before line 53, you can use it in the open.

2021-05-21 14:08 UTC, bneradt commented on tests/gold_tests/autest-site/verifier_client.test.ext
> +                 replay file.
Looks like we want to remove: "is supported"

2021-05-21 14:08 UTC, bneradt commented on tests/gold_tests/autest-site/verifier_server.test.ext
> +                 replay file.
Looks like we want to remove: "is supported"

2021-05-21 16:42 UTC, bneradt commented on tests/gold_tests/autest-site/verifier_client.test.ext
> +        KeyError if placeholders are missing from the mapping between context and the replay
"replay" -> "replay file."

2021-05-24 14:41 UTC, brbzull0 commented
[approve ci autest]

2021-05-24 14:55 UTC, bneradt approved these changes
Looks really helpful. Thank you Damian!

2021-05-24 16:05 UTC, brbzull0 commented
[approve ci autest]

2021-05-24 17:11 UTC, randall approved these changes

2021-05-24 18:02 UTC, merged

2021-08-05 20:46 UTC, zwoop commented
Cherry-picked to v9.1.x branch.