Fixed memory leak in the QUIC stream manager
apache/trafficserver pull request #7951
Opened 2021-06-17 15:36 UTC by bryancall

Removed the proxy allocator for the streams.  They can be added back in if there is a performance issue.

2021-06-17 17:59 UTC, bneradt requested changes
Looks good.

2021-06-17 17:59 UTC, bneradt commented on iocore/net/quic/QUICStreamManager.h
> +  }
Probably best to declare `~QUICStreamManager()` here and define in the `.cc` file. That will be consistent with the rest of the functions here.

2021-06-17 18:20 UTC, bryancall commented
[approve ci autest]

2021-06-17 21:11 UTC, bneradt approved these changes

2021-06-17 22:58 UTC, bryancall commented
[approve ci ubuntu]

2021-06-17 23:00 UTC, bryancall commented
[approve ci autest]

2021-06-18 00:20 UTC, maskit approved these changes

2021-06-18 00:20 UTC, maskit commented
[approve ci autest]

2021-06-18 01:06 UTC, bryancall commented
[approve ci autest]

2021-06-18 02:07 UTC, maskit commented
[approve ci autest]

2021-06-18 18:32 UTC, bneradt commented
[approve ci autest]

2021-06-18 23:04 UTC, merged