Clean up of next hop HostRecord class.
apache/trafficserver pull request #8585
Opened 2022-01-06 23:20 UTC by ywkaras

2022-01-06 23:48 UTC, rob05c commented
I have very mixed feelings about this.

An ideal solution isn't apparent. Every option has pros and a lot of cons.

>  HostRecord(const HostRecord &) = delete;
>  HostRecord &operator=(const HostRecord &) = delete;

I'm a big fan of deleting the copy and move - HostRecord conceptually should never be copied after initialization.

> struct HostRecord : public ATSConsistentHashNode, public HostRecordCfg {

Not such a big fan of the multiple inheritance. I think the pains of multiple inheritance go without saying.

But the multiple inheritance can easily be avoided by using composition instead. I see the complexity as the bigger question.

Bigger picture, this adds another layer of abstraction, for a very small object. It's an awful lot of complexity for what really ought to be a dead-simple POD class.

Is it really worth all this complexity, the added readability and maintainability costs, to reduce the chance of one small type of bug? I honestly don't know.

Also, this code is potentially leaving `ATSConsistentHashNode.available` uninitialized. Either the `HostRecord` constructor needs to set `available = true;`, or `ATSConsistentHashNode` needs its constructor modified to.

> HostRecord(HostRecordCfg &&o) : HostRecordCfg(o) {}

Is this necessary? I don't think anything besides YAML::Node copies or moves HostRecord, I'd be inclined to delete the move constructor as well.

2022-01-07 20:03 UTC, jrushford requested changes

2022-01-07 20:43 UTC, jrushford commented on proxy/http/remap/NextHopSelectionStrategy.h
> +  std::mutex _mutex;
oh, I see.  never mind, you added **= delete**

2022-01-10 16:48 UTC, ywkaras commented
I guess I was figuring that, since the PR makes the code more than 30 lines shorter, it was making it less complicated.  But maybe I just think too simplistically since I didn't go to graduate school.

2022-01-10 16:56 UTC, jrushford commented on proxy/http/remap/NextHopSelectionStrategy.h
> +  std::mutex _mutex;
I think it's fine now, I didn't notice you deleted the operator = and copy constructor.  This make for less maintenance if someone adds a field.

2022-01-10 17:16 UTC, rob05c commented
> I guess I was figuring that, since the PR makes the code more than 30 lines shorter, it was making it less complicated

I don't agree that lines of code is a strong indicator of complexity, or difficulty to read and maintain. Thirty lines fewer of assembly would not be less complex, but 30 lines more of Go probably would be.

I do see an additional layer of abstraction, another class, and multiple inheritance as more complex.

But as I said, I have mixed feelings, and I do agree there are advantages. I won't object if @jrushford or anyone else wants to approve.

2022-01-10 19:04 UTC, ywkaras commented
It's accurate to observe that I'm using inheritance for something that is not intuitively an is-a relationship.  I could instead have a HostRecordCfg substructure, instead of a base class, but that would mean more changes to the existing code.  But it's fairly common to use inheritance in "tricky" ways in C++:  https://stackoverflow.com/questions/4041447/how-is-stdtuple-implemented

2022-01-11 00:10 UTC, jrushford approved these changes
looks good to me

2022-01-11 01:16 UTC, merged

2022-01-18 15:45 UTC, zwoop commented
Cherry-picked to v9.2.x