Adds a simple tool to generate new escape tables
apache/trafficserver pull request #8783
Opened 2022-04-06 00:19 UTC by elsloo

2022-04-12 16:14 UTC, bneradt requested changes
Looks good. I just have a few minor suggestions. I made a PR for your fork with these suggestions here:

https://github.com/elsloo/trafficserver/pull/1

Feel free to pull that in, make changes, or discard it.

2022-04-12 16:14 UTC, bneradt commented on tools/Makefile.am
> +endif
Let's add `tools/escape_mapper/escape_mapper` to the .gitignore file.

2022-04-12 16:14 UTC, bneradt commented on tools/escape_mapper/escape_mapper.c
> +  // default characters supported by the codes_to_escape table found in LogUtils.cc
It would be good to add a comment above codes_to_escape requesting developers who modify it to modify this tool.

2022-04-18 16:24 UTC, elsloo commented
> Looks good. I just have a few minor suggestions. I made a PR for your fork with these suggestions here:
> 
> [elsloo#1](https://github.com/elsloo/trafficserver/pull/1)
> 
> Feel free to pull that in, make changes, or discard it.

Thanks for the assist; I just merged it in. I wrote this very quickly as a standalone tool, so I appreciate the help turning it into something that more closely resembles an existing ATS tool.

2022-04-18 16:28 UTC, bneradt approved these changes
Looks good to me.

2022-04-18 17:34 UTC, merged

2022-04-20 15:33 UTC, zwoop commented
Cherry-picked to v9.2.x