Add TCP info from server socket
apache/trafficserver pull request #8813
Opened 2022-04-29 00:00 UTC by serrislew

Current tcpinfo condition from header_rewrite plugin only provides tcp info from the client socket. 
- Adding a CLIENT and SERVER qualifier within this condition will provide tcp info from both client and server sockets. This could be beneficial in getting more info on the server connection behavior

2022-04-29 18:07 UTC, shukitchan commented
Please add to the existing documentation as well. thanks.

2022-05-02 23:10 UTC, SolidWallOfCode commented
I thought we were shifting to using the terms "INBOUND" and "OUTBOUND" instead of "CLIENT" and "SERVER".

2022-05-06 15:30 UTC, bryancall submitted a review, later dismissed

2022-05-06 16:06 UTC, zwoop commented
As per amc's question, I wonder if this should be changed to e.g.

```
%{INBOUND:TCPINFO}
```

? Also, this patch (or the above) would both be incompatible with current version of ATS 9.x right? As such, we can't put such a change into 9.x, unless you keep the old variation and add the new as an addition.

2022-05-06 16:07 UTC, zwoop requested changes
Marking as needing changes, while we discuss / resolve the issues around compatibility, and INBOUND vs CLIENT.

2022-05-06 17:30 UTC, serrislew commented
New changes should still be compatible. Without qualifiers, it defaults to previous behavior, using the client (inbound) socket.

2022-05-13 17:05 UTC, serrislew commented
[approve ci]

2022-07-11 18:12 UTC, bryancall approved these changes

2022-08-29 23:50 UTC, bryancall commented
[approve ci autest]

2022-08-29 23:52 UTC, bryancall commented
[approve ci]

2022-12-06 02:01 UTC, closed without merging