Deprecate TSSslSecretGet (not thread safe).
apache/trafficserver pull request #8862
Opened 2022-05-24 16:39 UTC by ywkaras

The current version is not thread safe because it returns a pointer into a mutex-protected data structure, which may be invalidated by another thread

2022-05-24 22:39 UTC, bneradt commented
Looks good. It's good to give a heads-up to people that this function signature will be changing in 10.x.

I suggest providing a brief description of the new signature now in these comments.

2022-05-25 01:59 UTC, ywkaras commented
The description is available in the Rel 10 documentation though.

2022-05-25 17:07 UTC, maskit commented
Do we deprecate things on minor releases? I feel like we've been doing it only on major releases but I'm not sure.
If it's deprecated on 9.2.0, what's the alternative way that is not deprecated on the version?

2022-05-25 19:37 UTC, maskit commented
Is the change #8790? It isn't even approved. Do we have consensus on the way of depreciation, which only changes the return type and the arguments?

I also found that `TSSslSecretGet` was introduced by #6609 and its milestone is 9.2.0, which means the API haven't been released publicly. If it's true, I think we can just remove the API.

2022-05-25 19:38 UTC, maskit commented on include/ts/ts.h
> +/* NOTE:  TSSslSecretGet() is deprecated, is is not thread-safe.  It will be replaced with a thread-safe function
typo: is is -> it is

2022-05-25 19:40 UTC, maskit requested changes
I'm not sure if this deprecation is needed in the first place.

The typo should be fixed anyway.

2022-05-25 19:55 UTC, ywkaras commented
> Is the change #8790? It isn't even approved. Do we have consensus on the way of depreciation, which only changes the return type and the arguments?
> 
> I also found that `TSSslSecretGet` was introduced by #6609 and its milestone is 9.2.0, which means the API haven't been released publicly. If it's true, I think we can just remove the API.

I was told not to mark #8790 for back port to 9.2.  If #8790 is rejected, we will have to eliminate or replace TSSslSecretGet() in another PR, it is not thread safe.  #8790 is currently running in Yahoo prod, I was waiting for it to soak for a while before trying to merge it in open source.

2022-05-25 20:09 UTC, maskit commented
> I was told not to mark https://github.com/apache/trafficserver/pull/8790 for back port to 9.2

I wonder why. Backporting it to 9.2 is another option indeed.

2022-05-25 20:14 UTC, ywkaras commented
> > I was told not to mark #8790 for back port to 9.2
> 
> I wonder why. Backporting it to 9.2 is another option indeed.

@bryancall do we want to reconsider back porting?

2022-06-02 13:23 UTC, ywkaras commented on include/ts/ts.h
> +** in Release 10 */
TS_MAYBE

2022-06-07 20:19 UTC, ywkaras commented
This won't be needed if https://github.com/apache/trafficserver/pull/8854 makes it into 9.2.

2022-09-13 02:17 UTC, closed without merging