Clean up ASAN noise from DbgCtl.cc.
apache/trafficserver pull request #9004
Opened 2022-08-08 15:31 UTC by ywkaras

2022-08-10 19:18 UTC, ywkaras commented on configure.ac
> +  TS_ADDTO(AM_CFLAGS, [-fno-omit-frame-pointer -fsanitize=address -DIS_ASAN_BUILD])
I originally wanted to add an "is ASAN build" flag to ink_config.h, but I couldn't figure out how to do it.

2022-08-29 23:48 UTC, bryancall commented
[approve ci autest]

2022-09-08 20:58 UTC, ywkaras commented
[approve ci autest]

2022-09-08 21:34 UTC, ywkaras commented
Ideally, all Au tests should run with a ASAN build with no errors.  This PR doesn't full achieve that goal, but it does make ASAN much more usable.  It eliminates a lot of benign leak errors from the ASAN output.

2022-09-08 21:36 UTC, ywkaras commented on proxy/logging/LogConfig.cc
> +    }
This fixes a small actual (non-spurious) leak.

2022-09-08 21:36 UTC, ywkaras commented on src/traffic_server/traffic_server.cc
> +    ats_free(hostname);
This fixes a small actual (non-spurious) leak.

2022-09-15 21:05 UTC, cmcfarlen requested changes
This pointer registry is used to keep track of allocations in two poorly designed places in the code.  I think we could refactor those and until then just tell the leak sanitizer to ignore the two functions where the allocations occur.  One place is because of a global un-owned pointer(a big no-no in modern C++) and the other is a naked union(another no-no).  Both situations are described in the C++ core guidelines (this is my appeal to authority, such that the core guidelines are). Having this registry condones bad coding practices and I don't think we should include it.

2022-09-15 21:09 UTC, moonchen commented
There is an documented way in LeakSanitizer to ignore leaks: https://github.com/google/sanitizers/wiki/AddressSanitizerLeakSanitizer#suppressions.  We should use that method if we want to ignore leaks.

If we want to change the code to remove the leak, we should do it in a way that removes it in both sanitizer and non-sanitizer builds.  Having different code for sanitizer vs non-sanitizer should be a last resort since it defeats the verification function of the sanitizers.

2022-09-20 15:04 UTC, ywkaras commented
The intent of this PR is to make ASAN more usable.  Much of ATS could politely be called "pre-Modern", but there doesn't seem to be consensus to make addressing that a priority.  There has to be consensus on strategic goals.  If we all start blocking PRs to try to enforce what we individually think strategic goals should be, that's a recipe for gridlock.

The registry only identifies and filters "leaks" that have been determined to be benign.  It doesn't defeat the purpose of the sanitizer.  To me, it seems more maintainable than a single file with a vague(pattern-based) list of all the benign leaks.

2022-09-20 19:12 UTC, ywkaras commented on src/records/RecUtils.cc
> +      OwningPtrRegistry::add_raw(&(data_dst->rec_string), data_dst->rec_string);
Generally one should look at change raw unions to std::variants.  But that's beyond the scope of this PR.

2022-09-20 22:22 UTC, cmcfarlen commented on src/records/RecUtils.cc
> +      OwningPtrRegistry::add_raw(&(data_dst->rec_string), data_dst->rec_string);
Agreed.  A std::variant would be better!

2022-09-20 22:25 UTC, cmcfarlen commented
I prefer the file as its easier to reason about and it doesn't come with incidental code.

2022-09-20 22:41 UTC, ywkaras commented
> I prefer the file as its easier to reason about and it doesn't come with incidental code.

I don't understand "reason about".  To me, when something is added to the registry, it clarifies the intent to allow process exit to clean up the allocation.  Without having to go look in a separate file, remember the precise format of the ASAN output.  Doesn't look like the meaning of "pattern" is well documented, whether it's a full regex, etc.  What would the leak suppressor do if a pattern matched no leak?  The registry can handle it if whether or not something is deallocated by process exit depends on runtime circumstances.

2022-09-20 22:49 UTC, cmcfarlen commented
I just mean that when you are doing "ASAN" things and looking for leaks, all of the excluded ones are all in one place.  This way managed with code is incidental to anything else.  Also, we don't need to invent a new method to mark "benign" leaks when one is already provided.

2022-09-20 23:08 UTC, ywkaras commented
When something is provided, one also has to consider how well documented and therefore usable it is.

2022-10-11 16:04 UTC, ywkaras commented
[approve ci autest]

2022-10-11 16:34 UTC, ywkaras commented
OK the registry is gone.

2022-10-17 23:49 UTC, cmcfarlen approved these changes

2022-10-18 00:03 UTC, merged