Support reverse lookups from the host file.
apache/trafficserver pull request #9043
Opened 2022-08-17 21:40 UTC by cmcfarlen

Refactor host file code to make it more testable and unify lookups
Add unit test for HostFile

2022-08-17 21:40 UTC, cmcfarlen commented
Fixes #9025

2022-08-18 19:04 UTC, cmcfarlen commented
While this supports reverse lookups from the hosts file, there is some issue with deterministic selection of the name that is resolved for a given IP since the order depends on the appearance of the file as well as how we parse the hosts file.  Currently the unit test is broken because of this nondeterministic behavior.  Should we try to guarantee a deterministic resolution or should we just return any host with the assigned IP?  I'm not sure how ATS handles multiple hosts returned from a reverse lookup currently.

Should this "reverse lookup from the hosts file" be a configurable feature?

2022-08-20 19:28 UTC, SolidWallOfCode commented
Is it indeterminate because an unordered map is used? I think it would be fine to say which ever name is first associated with an IP address is the reverse lookup name.

2022-08-20 19:33 UTC, SolidWallOfCode commented on iocore/hostdb/HostFile.cc
> +using HostAddrMap = std::unordered_map<std::string_view, std::tuple<std::vector<IpAddr>, std::vector<IpAddr>>>;
If you're going to split it anyway, you might as well use `Ip4Addr` and `Ip6Addr`.

2022-08-21 21:23 UTC, SolidWallOfCode commented
I wonder if `Lexicon` would work in this situation. It supports primary and secondary names vs. a numeric value, which seems like the situation here.

2022-08-29 23:54 UTC, bryancall commented
[approve ci autest]

2022-09-21 23:34 UTC, SolidWallOfCode approved these changes

2022-09-21 23:42 UTC, maskit requested changes, later dismissed
Is this for 10-Dev or not? It's marked as 10-Dev but the target branch is master.

2022-09-22 14:39 UTC, cmcfarlen commented
> Is this for 10-Dev or not? It's marked as 10-Dev but the target branch is master.

I moved it to 10.0 milestone but idk how to remove it from the 10-dev project.

2022-09-22 14:54 UTC, bneradt commented
> > Is this for 10-Dev or not? It's marked as 10-Dev but the target branch is master.
> 
> I moved it to 10.0 milestone but idk how to remove it from the 10-dev project.

I removed it. I just uncheck-marked the 10-Dev project.

2022-09-22 14:56 UTC, cmcfarlen commented
> > > Is this for 10-Dev or not? It's marked as 10-Dev but the target branch is master.
> > 
> > 
> > I moved it to 10.0 milestone but idk how to remove it from the 10-dev project.
> 
> I removed it. I just uncheck-marked the 10-Dev project.

Thanks, I must not have that permission as I didn't see a checkmark to uncheck!

2022-09-23 01:01 UTC, merged