Fail sni.yaml loading if related resources fail to load
apache/trafficserver pull request #9132
Opened 2022-10-10 16:17 UTC by randall

Fixes #9093

2022-10-10 16:19 UTC, randall commented
This should go into 9.2 and probably others, but they'll require version specific PRs due to slight source reorg/rename.

2022-10-10 23:04 UTC, ywkaras commented
[approve ci autest]

2022-10-10 23:18 UTC, ywkaras commented
Looks like there is a hard fail for Au test tls_check_cert_selection_reload.

2022-10-11 00:20 UTC, randall commented
> Looks like there is a hard fail for Au test tls_check_cert_selection_reload.

Thanks, I think I got it happy now.

2022-10-11 19:10 UTC, bneradt requested changes
Looks good to me.

Do you think we can add an autest to verify this? Alan wrote some tests for remap reload failure with the following PR, in case that's helpful:

https://github.com/apache/trafficserver/pull/8802/files

2022-10-12 20:35 UTC, randall commented
> Looks good to me.
> 
> Do you think we can add an autest to verify this? Alan wrote some tests for remap reload failure with the following PR, in case that's helpful:
> 
> https://github.com/apache/trafficserver/pull/8802/files

Added (thanks to @cmcfarlen !)

2022-10-13 15:09 UTC, bneradt requested changes
Looks great. Thank you for working on the test. I just have a few minor updates for it.

2022-10-13 15:09 UTC, bneradt commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +])
`f"""` with `.split('\n')`:

```
ts.Disk.sni_yaml.AddLines(
      f"""                                    
      sni:                                    
      - fqdn: {sni_domain}                                    
        http2: off                                    
        client_cert: {ts.Variables.SSLDir}/signed-foo.pem                                    
        client_key: {ts.Variables.SSLDir}/signed-foo.key                                    
        verify_client: STRICT                                    
      """).split('\n')                                    
 )

2022-10-13 15:22 UTC, randall commented
oops, I didn't release you added more comments @bneradt. Sorry for the re-review request.

2022-10-13 15:24 UTC, randall commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +ts = Test.MakeATSProcess("ts", command="traffic_manager", select_ports=True, enable_tls=True)
We should go through and cleanup the 119 other `select_ports=True` in a separate PR too (I (and probably others) just copy/paste from existing tests to make the system happy)

2022-10-13 16:14 UTC, randall commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +ts = Test.MakeATSProcess("ts", command="traffic_manager", select_ports=True, enable_tls=True)
Created #9142 for select_ports cleanup

2022-10-13 17:49 UTC, randall commented
[approve ci autest]

2022-10-13 18:08 UTC, bneradt commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +ts = Test.MakeATSProcess("ts", command="traffic_manager", select_ports=True, enable_tls=True)
Thanks Randall. Approved.

2022-10-13 19:18 UTC, randall commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +#ts.Disk.diags_log.Content = Testers.ContainsExpression('ERROR: ', 'ERROR')
restored.

2022-10-13 19:18 UTC, randall commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +#tr3.Processes.Default.StartBefore(server2, ready=When.FileContains(ts.Disk.diags_log.Name, 'unknown value "BROKEN"', 1))
added

2022-10-13 19:18 UTC, randall commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +ts.Disk.diags_log.Content = Testers.IncludesExpression("SSL negotiation finished successfully", "negotiation failed")
added

2022-10-13 19:18 UTC, randall commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +])
done in both places.

2022-10-13 21:44 UTC, bneradt commented on tests/gold_tests/tls/tls_sni_yaml_reload.test.py
> +ts.Disk.diags_log.Content = Testers.IncludesExpression("SSL negotiation finished successfully", "negotiation failed")
Thanks, the first two looks good. But can you change the `"negotiation failed"` to something like `"Verify that the TLS handshake was successful."`.

As it is, if the match failed, the failure message will look something like:

```
       file <some_path>/diags_log : negotiation failed - Failed
```

That would look like it's saying we wanted the negotiation to fail, but instead it failed to fail.

Anyway, all the other Expression strings in the test look fine.

2022-10-13 22:37 UTC, bneradt approved these changes
Looks good to me.

2022-10-13 23:06 UTC, merged

2022-10-17 22:52 UTC, zwoop commented
Cherry-picked to v9.2.x