libswoc - replace string_view_util with libswoc version.
apache/trafficserver pull request #9203
Opened 2022-11-17 18:44 UTC by SolidWallOfCode

This is needed both to remove redundancy and to avoid circular dependencies, as libswoc internals depend on the functions in the `string_view` utils.

2022-11-17 19:31 UTC, SolidWallOfCode commented
[approve ci fedora]

2022-11-17 19:40 UTC, bneradt requested changes
Looks good.

2022-11-17 19:40 UTC, bneradt commented on lib/swoc/include/swoc/string_view_util.h
> + * Therefore @a dst must point at a buffer large enought to hold @a src. If this is not already
enought

2022-11-17 19:43 UTC, bneradt commented
The builds are failing due to linking issues. Here's a link to the Ubuntu failure:
https://ci.trafficserver.apache.org/job/Github_Builds/job/ubuntu/389/console

2022-11-17 19:58 UTC, SolidWallOfCode commented
Oh, I'm tracking the linking issues. The problem is all of that works perfectly locally. This is part of resolving the linking issues with #9193 .

2022-11-18 01:58 UTC, SolidWallOfCode commented
[approve ci rocky]

2022-11-18 02:37 UTC, SolidWallOfCode commented
Seriously? That was the fix? Gah.

2022-11-18 03:02 UTC, SolidWallOfCode commented
Seriously? That fix worked? Gaaaaaaaaaaaaaaaaaaaaaaah!

2022-11-18 16:38 UTC, bneradt approved these changes

2022-11-18 18:39 UTC, merged