Add TSHttpTxnNextHopPortGet, add to header rewrite
apache/trafficserver pull request #9829
Opened 2023-06-12 15:01 UTC by traeak

This adds TSHttpTxnNextHopPortGet in addition to TSHttpTxnNextHopNameGet and exposes to header_rewrite as %{NEXT-HOP:NAME} and %{NEXT-HOP:PORT}.

2023-06-12 15:18 UTC, shukitchan requested changes
I think you are still working on this. 
But please update the plugin documentation on the new changes as well. Thanks.

2023-06-21 16:35 UTC, traeak commented
[approve ci rocky]

2023-06-22 13:44 UTC, traeak commented
> I think you are still working on this. But please update the plugin documentation on the new changes as well. Thanks.

it was just wip.  should be documented and everything.

2023-06-28 08:41 UTC, shukitchan requested changes
Also, I think we need to update documentation for header rewrite plugin as well.

2023-06-28 08:41 UTC, shukitchan commented on doc/developer-guide/api/functions/TSHttpTxnNextHopPortGet.en.rst
> +.. function:: const char *TSHttpTxnNextHopPortGet(TSHttpTxn txnp)
The return type is int instead. A typo here?

2023-06-28 14:53 UTC, shukitchan approved these changes

2023-06-29 15:37 UTC, merged

2023-07-03 16:31 UTC, zwoop commented
Slightly unorthodox to include this in a patch release, but alas, we're not doing 9.3.0 release, and this seems generally useful and safe.