records.yaml  - conf_remap update to use records.yaml as files.
apache/trafficserver pull request #9942
Opened 2023-07-03 11:12 UTC by brbzull0

A follow up from the conversion from `records.config` to `records.yaml`, now this PR updates the `conf_remap`  plugin to use YAML files as input files. That is beside the inline variable style which **does not change** the plugin can now parse `YAML` files.
The plugin does not support `.config` files for config variables anymore, `YAML` should be used instead.

Autest is also updated and a new one is introduced.

2023-07-03 11:51 UTC, brbzull0 commented
[approve ci autest]

2023-07-03 12:26 UTC, brbzull0 commented
[approve ci]

2023-07-31 20:51 UTC, cmcfarlen requested changes
Do we need to check str post-coercion or can we just check IsNull?

2023-08-02 11:39 UTC, brbzull0 commented on plugins/conf_remap/conf_remap.cc
> +      if (str == "NULL") {
> Or are we wanting user to be able to specify a 'NULL' string

Yes, user can say, NULL and NULL means something different than the `YAML` value `null|~|Null` 

like (not the best example as this is not overridable, but it helps to see how it behaves):
```yaml
ts:
  dns:
    resolv_conf: "NULL"
```

this part of the plugin seems to mimic what ats does [internally](https://github.com/apache/trafficserver/blob/6cfb2c4d0a62b383a1375f3ba109e70d14137126/src/records/RecUtils.cc#L360) for string record parsing.

2023-08-03 14:32 UTC, brbzull0 commented on plugins/conf_remap/conf_remap.cc
> +      if (str == "NULL") {
@cmcfarlen  : I've enhanced the null check to add `value.isNull()` as part of the condition. I think both means null in terms of ATS.  
Also, while testing this out I found a potential issue which I've fixed [here](https://github.com/apache/trafficserver/pull/10135) (already merged). Thanks

2023-08-04 18:33 UTC, cmcfarlen approved these changes

2023-08-09 08:58 UTC, merged