Add libloader plugin to CMake build
apache/trafficserver pull request #9953
Opened 2023-07-05 17:07 UTC by JosiahWI

This builds the libloader plugin with CMake, and fixes a typo in a comment in healthchecks/CMakeLists.txt which I copied part of for these changes.

2023-07-05 18:37 UTC, JosiahWI commented
[ci approve autest]

2023-07-05 18:50 UTC, JosiahWI commented
[approve ci autest]

2023-07-05 20:56 UTC, cmcfarlen requested changes
instead of clearing out the compile options, we could mark the problem option as cxx only:
```
add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-Wno-invalid-offsetof>)
```

2023-07-06 16:34 UTC, cmcfarlen approved these changes

2023-07-06 17:09 UTC, merged